name: Build and upload release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build application
        run: |
          cargo build --release
          zip --junk-paths glot-run-data-decoder target/release/glot-run-data-decoder

      - name: Debug
        run: |
            cat $GITHUB_EVENT_PATH

      - name: Expose upload_url
        run: |
          UPLOAD_URL=$(cat $GITHUB_EVENT_PATH | jq -r '.release.upload_url')
          echo "::set-env name=UPLOAD_URL::$UPLOAD_URL"

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: $UPLOAD_URL
          asset_path: glot-run-data-decoder.zip
          asset_name: glot-run-data-decoder.zip
          asset_content_type: application/zip
